import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SolanaContext } from "./utils/solWalletProvider";

const cosmicSans = localFont({
  src: "./fonts/CosmicMS.ttf",
  variable: "--font-cosmic-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cosmicSans.variable}`}>
        <SolanaContext>{children}</SolanaContext>
      </body>
    </html>
  );
}
